// Code generated by "stringer -type=Operation"; DO NOT EDIT.

package day6

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[OpSum-43]
	_ = x[OpMul-42]
}

const _Operation_name = "OpMulOpSum"

var _Operation_index = [...]uint8{0, 5, 10}

func (i Operation) String() string {
	idx := int(i) - 42
	if i < 42 || idx >= len(_Operation_index)-1 {
		return "Operation(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Operation_name[_Operation_index[idx]:_Operation_index[idx+1]]
}
